name: CI Build

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2.4.2
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: '5.x'
        
    - name: Display GitVersion config
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.13
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml
        additionalArguments: "/updateprojectfiles"
        
    - name: Display GitVersion outputs
      run: |
        echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
        echo "InformationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}"  

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish src/OpServer.Web/Opserver.Web.csproj -c Release -o website --self-contained -r win-x64
      
    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v1.2.0
      with:
        version: latest

    - name: Package for Octopus        
      run: |
        octo pack --id="Wizardsoft.OpServer" --format="Zip" --version=${{ steps.gitversion.outputs.informationalVersion }} --basePath="Website" --outFolder="$GITHUB_WORKSPACE/artifacts"

    - name: Push packages to Octopus
      uses: OctopusDeploy/push-package-action@v1.1.2
      with:
        api_key: ${{ secrets.OCTOPUS_API_KEY }}
        server: ${{ secrets.OCTOPUS_SERVER_URL }} 
        packages: "artifacts/Wizardsoft.OpServer.${{ steps.gitversion.outputs.informationalVersion }}.zip"